
spring:
  application:
    name: firstjobapp
  datasource:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
 
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
        
info:
  app:
   name: JobApplication
  description: Job App Build By Haridas Chavan
  version:
   1.0.0 
   
server:
  shutdown:
      graceful
   